[tool.poetry]
name = "chinko-gen-py"
version = "0.1.0"
description = ""
readme = "README.md"
packages = [{include = "chinko_gen_py"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
